//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagement {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ProcessManagmentSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ProcessManagmentSettings defaultInstance = ((ProcessManagmentSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ProcessManagmentSettings())));
        
        public static ProcessManagmentSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ProcessFetchIntervalInSeconds {
            get {
                return ((int)(this["ProcessFetchIntervalInSeconds"]));
            }
            set {
                this["ProcessFetchIntervalInSeconds"] = value;
            }
        }
    }
}
